### PR TITLE
Add CLI argument to configure healthcheck path

### PR DESCRIPTION
**Pull request by toadjaune**
## Context

The `/status` path might not be available (used by the php code for its own healthcheck, for example).

This MR allows to configure it through an environment variable.

## Changes

- [ ] Tests included
- [ ] Documentation updated
- [x] Commit message is clear

### CODE REVIEW

**Comment by jelovac** [comment]
Hi @renatomefi,

Can you check this pull request?

**Comment by deiga** [comment]
This would be very much needed!

**Comment by renatomefi** [comment]
Sure thing! I'm checking what's happening to the `test-latest` build, not sure if php of cgi cli has changed something, doesn't seem blocker tho

**Comment by renatomefi** [comment]
Thanks @toadjaune! I've taken over your PR to add tests and docs, I've kept your commit authorship!

@jelovac @deiga it's now available in version 0.5.0!

Have a great day everyone!

**Pull request closed without merging**
